language: node_js

node_js:
  - 12

services:
  - docker

before_script:
  - npm install
  - npm run installDeps:app
  - npm run installDeps:api

stages: 
  - name: build
    if: branch = travis
  - name: test
    if: branch = master

jobs:
  include:
    - stage: test
      install: skip
      script:
        - npm run test
        - npm run lint

    - stage: build
      install: skip
      script:
        - bash docker_build
