language: node_js

node_js:
  - 12

services:
  - docker

before_script:
  - npm install
  - npm run installDeps:app
  - npm run installDeps:api

stages: 
  - name: build
    if: tag IS present
  - name: test
    if: tag IS blank

jobs:
  include:
    - stage: test
      install: skip
      script:
        - npm run test
        - npm run lint

    - stage: build
      install: skip
      script:
        - docker build -t gennadiixd/hello-world-api:${TRAVIS_TAG} ./api
        - docker build -t gennadiixd/hello-world-app:${TRAVIS_TAG} ./app
        - docker login -u "$DOCKER_USERNAME" -p "${DOCKER_PASSWORD}"
        - docker push gennadiixd/hello-world-api:${TRAVIS_TAG}
        - docker push gennadiixd/hello-world-app:${TRAVIS_TAG}
