language: node_js

node_js:
  - 12

services:
  - docker

before_script:
  - npm install
  - npm run installDeps:app
  - npm run installDeps:api

script:
  - npm run test
  - npm run lint

deploy:
  provider: script
  script:
    - bash docker_deploy
  on:
    tags: true
