language: node_js

node_js:
  - 12

services:
  - docker

before_script:
  - npm install
  - npm run installDeps:app
  - npm run installDeps:api

before_install:
  - docker build -t gennadiixd/hello-world-api${TRAVIS_TAG} ./api
  - docker build -t gennadiixd/hello-world-app${TRAVIS_TAG} ./app

script:
  - npm run test
  - npm run lint

deploy:
  provider: script
  script: bash docker_push
  on:
    tags: true