version: "3"
services:
  server:
    image: nginx
    container_name: nginx-proxy
    restart: always
    volumes:
     - "../config/nginx/nginx.prod.conf:/etc/nginx/nginx.conf"
     - "/etc/letsencrypt:/etc/nginx/certs"
     - "./../tmp/images:/public/images"
    ports:
      - "80:80" 
      - "443:443" 
    links: # Link services to access http://app and  http://api inside the container
      - api:api
      - app:app
  app:
    image: gennadiixd/hello-world-app:${TAG}
    container_name: ssr-app
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=5000 # port inside container
      - HOST=0.0.0.0 # host to bind inside container
      - API_BASE=https://test-project.online/api
    ports:
      - "5000:5000" # For docker to now where to redirect HMR queries
    stdin_open: true
    links:
      - api:api
  api:
    image: gennadiixd/hello-world-api:${TAG}
    container_name: api
    restart: always
    environment:
      - DB_NAME=myappdb
      - DB_USER=myappuser
      - DB_PASSWORD=myapppassword
      - DB_HOST=db
      - DB_PORT=5432
      - NODE_ENV=production
    links:
      - db:db
    volumes:
      - ./../tmp/images:/api/public/images
    ports:
      - "3000:3000"
  db:
    image: postgres:9.5
    container_name: db
    environment:
      - POSTGRES_USER=myappuser
      - POSTGRES_PASSWORD=myapppassword
      - POSTGRES_DB=myappdb
    volumes: 
      - "./../tmp/postgres:/var/lib/postgresql/data"
    ports:
      - "5431:5432"
