version: "3"
services:
  server:
    image: nginx
    container_name: nginx-proxy
    restart: always
    volumes:
      - "../config/nginx/nginx.dev.conf:/etc/nginx/nginx.conf"
      - "../certs:/etc/nginx/certs"
      - "./../tmp/images:/public/images"
    ports:
      - "443:443"
    links:
      - api:api
      - app:app
    networks:
      default:
        aliases:
          - myprojectdomain.dev
  app:
    image: node:12-alpine
    container_name: ssr-app
    restart: always
    environment:
      - NODE_EXTRA_CA_CERTS=/certs/minica.pem
      - NODE_ENV=development
      - PORT=5000 # port inside container
      - HOST=0.0.0.0 # host to bind inside container
      - API_BASE=https://myprojectdomain.dev/api
      - JWT_SECRET="${JWT_SECRET}"
    volumes: # For webpack dev server to use our local files
      - "./../app:/app"
      - "../certs/minica.pem:/certs/minica.pem"
    working_dir: "/app"
    entrypoint: /bin/sh -c "npm i && npm run start:dev"
    ports:
      - "5000:5000" # For docker to now where to redirect HMR queries
    stdin_open: true
    links:
      - api:api
  api:
    image: node:12-alpine
    container_name: api
    restart: always
    environment:
      - DB_NAME=myappdb
      - DB_USERNAME=myappuser
      - DB_PASSWORD=myapppassword
      - DB_HOST=db
      - DB_PORT=5432
      - TYPEORM_SYNC=true
      - NODE_ENV=development
      - WAIT_HOSTS=db:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - JWT_SECRET="${JWT_SECRET}"
    links:
      - db:db
    volumes:
      - ./../api:/api
      - ./../tmp/images:/api/public/images
    working_dir: /api
    entrypoint: /bin/sh -c "npm i && npm run start:dev"
    ports:
      - "3000:3000"
  db:
    image: postgres:9.5
    container_name: db
    environment:
      - POSTGRES_USER=myappuser
      - POSTGRES_PASSWORD=myapppassword
      - POSTGRES_DB=myappdb
    volumes: 
      - "./../tmp/postgres:/var/lib/postgresql/data"
    ports:
      - "5431:5432"
