export const SET_PRODUCTS = "SET_PRODUCTS";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const SET_CURRENT_PRODUCT = "SET_CURRENT_PRODUCT";
export const SET_PRODUCTS_PAGE = "SET_PRODUCTS_PAGE";
export const SET_SEARCH_STATE = "SET_SEARCH_STATE";
